# Build the builder docker image
FROM python:3.8-slim

WORKDIR /opt/main
COPY Pipfile* ./
RUN apt-get update \
    && apt-get install --no-install-recommends -yq make gcc libpq-dev libffi-dev libtool \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
